ignore:
  - "**/*.pb.go"
  - "go/consensus/tendermint/fuzz" # Fuzz tests.
  - "go/extra" # Extra packages.
  - "go/oasis-net-runner" # Test local network runner.
  - "go/oasis-node/cmd/debug" # Debug and test utilities.
  - "go/oasis-test-runner" # E2E test runner.
  - "go/registry/gen_vectors" # Registry test vector generator.
  - "go/staking/gen_vectors" # Staking test vector generator.
  - "go/governance/gen_vectors" # Governance test vector generator.
  - "go/storage/fuzz" # Fuzz tests.
  - "go/storage/mkvs/fuzz" # Fuzz tests.
  - "go/storage/mkvs/interop" # MKVS interoperability test helpers.
  - "runtime/src/storage/mkvs/interop" # MKVS interoperability test helpers.
